### ISSUE TITLE
some scripts are not tagged, but some are

### ISSUE THREAD

**Issue by stephenogg** [ome/omero-guide-python#35]
Hi OME Team -
I was updating my ansible scripts that install omero to fetch python scripts from this repository instead of the "training-scripts" repository as there is a message in the training scripts repository that the maintained scripts have been moved here. I ran into trouble with the scipy_gaussian_filter.py and simple_frap_with_figure.py because they are not tagged with the "0.1.0" tag, and therefore cannot be retrieved from a url that includes "/v0.1.0/" but have to be retrieved from the master branch. On the other hand, simple_frap.py is tagged and so a static, known version can be retrieved. I only explored those 3 scripts - not sure about others. Not a huge deal, but for consistency, would be nice to have the whole repository tagged, no? 
Thanks!

**Comment by jburel** [comment]
You are correct. Thanks for pointing that out. We will sort it

**Comment by jburel** [comment]
Tagged has been used. Closing
