### ISSUE TITLE
Failed to install in Windows 10

### ISSUE THREAD

**Issue by zoccoler** [ome/omero-guide-python#56]
Hi everyone,

I was trying to install this library in Windows 10 following the instructions from [here](https://github.com/ome/omero-guide-python#running-locally), but it fails to solve the environment. I tried it with `conda` and `mamba`.

`conda env create -n omero-guide-python -f binder/environment.yml`

```python

Collecting package metadata (repodata.json): done
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
```
It never ends to solve conflicts.

`mamba env create -n omero-guide-python -f binder/environment.yml`

```python
Looking for: ['python=3.9', 'dask', 'distributed', 'pip', 'omero-py', 'pandas', 'tensorflow=2.6', 'scikit-image']


Could not solve for environment specs
Encountered problems while solving:
  - package tensorflow-2.6.0-mkl_py39h31650da_0 is excluded by strict repo priority

The environment can't be solved, aborting the operation
```

Can someone reproduce this and help me install it? Thanks!

**Comment by jburel** [comment]
maybe try to modify the version of tensorflow. It is currently pin to 2.6.
The other packages have not been pinned (they should have been)

**Comment by jburel** [comment]
@zoccoler I have found a solution
I am about to open a pull request allowing to build on windows

**Comment by jburel** [comment]
See #57

**Comment by zoccoler** [comment]
Thank you @jburel , I can confirm that solved the installation problem! :)
