### ISSUE TITLE
Problem with local build of this env

### ISSUE THREAD

**Issue by pwalczysko** [ome/omero-guide-python#60]
The env builds okay, but I do not seem to be able to open a working browser window with

``jupyter notebook`` - just a white screen, the pasting of the suggested links into address bar does not help. The cmd is reporting intermittently non-existing kernel (note: I had to rename the to-be-created env to some other name in ``environment.yml`` as I was getting an error from mamba that ``prefix already exists``.

**Comment by jburel** [comment]
https://github.com/ome/omero-guide-python/pull/61
